export default {

	OPENSMLAYER: 'OPENSMLAYER',//slsm

	OPENZBLAYER: 'OPENZBLAYER',//slzb

	OPENQHLAYER: 'OPENQHLAYER',//slqh

	OPENDXLAYER: 'OPENDXLAYER', //打开训练定向界面

	//pk
	OPENMATCHPK: 'OPENMATCHPK',    //pk匹配

	OPENCHUANGUAN: 'OPENCHUANGUAN',

	OPENSETLAYER: 'OPENSETLAYER',//打开设置界面

	OPENHISTORYLAYER: 'OPENHISTORYLAYER',//打开历史记录界面

	OPENMONTHLAYER: 'OPENMONTHLAYER',//月报

	OPENYIELDLAYER: 'OPENYIELDLAYER',//收益曲线

	OPENPLAYERINFO: 'OPENPLAYERINFO',//玩家信息界面

	onCmdQuoteQuery: 'onCmdQuoteQuery', //查询行情

	HISTORYOPTDATA: 'GETHISTORYOPTDATA',
	//hall
	GOLDCHANGE: 'GOLDCHANGE', //金币改变

	DIAMONDCHANGE: 'DIAMONDCHANGE', //砖石改变

	LEVELCHANGE: 'LEVELCHANGE', //等级

	EXPCHANGE: 'EXPCHANGE', //经验

	HEADIMGCHANGE: 'HEADIMGCHANGE',//头像改变

	GENDERCHANGE: 'GENDERCHANGE',//性别修改

	NAMECHANGE: 'NAMECHANGE',   //name改变

	LOCALTIONCHANGE: 'LOCALTIONCHANGE',

	LOADINGSHOW: 'LOADINGSHOW', //加载显示

	LOADINGHIDE: 'LOADINGHIDE', //加载动画隐藏

	MABOLLSWITCH: 'MABOLLSWITCH',

	OPENHELPLAYER: 'OPENHELPLAYER',//打开帮助截面

	// HIDEOTHERNODE:'HIDEOTHERNODE',

	//  SHOWOTHERNODE: 'SHOWOTHERNODE',

	SMINITFUND: 'SMINITFUND', //双盲初始游戏金币

	OPENSMRESETMONEYLAYER: 'OPENSMRESETMONEYLAYER', //打开双盲重置金币页面

	CmdQuoteQueryFuture: 'CmdQuoteQueryFuture',  //// 查询期货行情

	BLACKGOTOLAYER: 'BLACKGOTOLAYER',

	GMAECOUNTERSCHANGE: 'GMAECOUNTERSCHANGE',  //输赢记录重置 或改变

	OPENCGSLVRANK: 'OPENCGSLVRANK',//打开闯关赛关卡排行

	GETCGSDATA: 'GETCGSDATA',//获取闯关赛数据

	OPENCJDZ: 'OPENCJDZ',  //创建对战

	OPENROOM: 'OPENROOM',//进入房间

	OPENJRDZ: 'OPENJRDZ',//加入对战

	INVITEMESSAGE: 'INVITEMESSAGE', //邀请消息

	ROOMOLAYERSTATUS: 'ROOMOLAYERSTATUS',//玩家准备就绪

	ROOMLEAVE: 'ROOMLEAVE',//玩家离开房间

	OPENZNXG: 'OPENZNXG',//打开智能选股

	OPENMYXG: 'OPENMYXG',//模拟选股

	OPENZGLAYER: 'OPENZGLAYER',//诊股

	OPENZNDRAW: 'OPENZNDRAW',

	//game
	ADDFILLCOLOR: 'ADDFILLCOLOR',

	GAMEOVEER: 'GAMEOVEER',

	HELPSHOW: 'HELPSHOW',

	SETMALABEL: 'SETMALABEL',       //均线LABEL

	GAMEFUPAN: 'GAMEFUPAN',         //游戏复盘

	SET_DRAW_SIZE: 'SET_DRAW_SIZE',   //设置画盘大小

	ONMARKUPDATE: 'ONMARKUPDATE',

	ONADDMARK: 'ONADDMARK',

	//RaisingLimit
	RAISINGLIMIT: "RAISINGLIMIT",//涨停板

	//	ONADDMARKAI: 'ONADDMARKAI',  //策略买卖标签

	UPDATERATE: 'UPDATERATE',  //跟新盈利率

	ONMARKRANGESHOWORHIDE: 'ONMARKRANGESHOWORHIDE',

	TIPSTEXTSHOW: 'TIPSTEXTSHOW',

	TIPSTEXTHIDE: 'TIPSTEXTHIDE',

	MYSPICCLICK: 'MYSPICCLICK',

	SLGEVENTNOTICE: 'SLGEVENTNOTICE',

	CLICKMOVE: 'CLICKMOVE',

	OPENSTATLAYER: 'OPENSTATLAYER',

	ADDMARKHIDEORSHOW: 'ADDMARKHIDEORSHOW',

	FILLNODEISSHOW: 'FILLNODEISSHOW',

	CREATEBLOCK: 'CREATEBLOCK',  //创建提示方块

	NOTICEDRAWMOVW: 'NOTICEDRAWMOVW',

	OPENSELECTBOX: 'OPENSELECTBOX',//分仓买入卖出

	CLICKFCBTN: 'CLICKFCBTN',//点击选择分仓

	SETMARKCOLOR: 'SETMARKCOLOR',    //标签颜色



	RoomGameDataSelf: 'RoomGameDataSelf',  //自己进入房间

	RoomGameDataOther: 'RoomGameDataOther',  //其他人进入房间

	RoomGameStatus: 'RoomGameStatus',	  //房间状态

	CUTGAMEFUPAN: 'CUTGAMEFUPAN',    //切换

	GAMEFUPANOPT: 'GAMEFUPANOPT',    //复盘操作

	PKFUPAN: 'PKFUPAN',    //pk复盘

	//: 'OPENOTHERINFOBOX',//其他玩家信息框

	CLEARINTERVAL: 'CLEARINTERVAL',  //竞技结束计时

	GAMEWAIT: 'GAMEWAIT',//游戏等待
};
