export default {
	//hall
	GOLDCHANGE: 'GOLDCHANGE', //金币改变

	BIRCKCHANGE: 'BIRCKCHANGE', //砖石改变

	LEVELCHANGE: 'LEVELCHANGE', //等级

	EXPCHANGE: 'EXPCHANGE', //经验

	NAMECHANGE: 'NAMECHANGE',

	LOADINGSHOW: 'LOADINGSHOW', //加载显示

	LOADINGHIDE: 'LOADINGHIDE', //加载动画隐藏

	MABOLLSWITCH: 'MABOLLSWITCH',

	OPENHELPLAYER: 'OPENHELPLAYER',//打开帮助截面

	// HIDEOTHERNODE:'HIDEOTHERNODE',

	//  SHOWOTHERNODE: 'SHOWOTHERNODE',

	SMINITFUND: 'SMINITFUND', //双盲初始游戏金币

	OPENSMRESETMONEYLAYER: 'OPENSMRESETMONEYLAYER', //打开双盲重置金币页面

	CmdQuoteQueryFuture: 'CmdQuoteQueryFuture',  //// 查询期货行情

	BLACKGOTOLAYER: 'BLACKGOTOLAYER',

	//game
	ADDFILLCOLOR: 'ADDFILLCOLOR',

	GAMEOVEER: 'GAMEOVEER',

	HELPSHOW: 'HELPSHOW',

	SETMALABEL: 'SETMALABEL',

	GAMEFUPAN: 'GAMEFUPAN',

	SET_DRAW_SIZE: 'SET_DRAW_SIZE',

	ONMARKUPDATE: 'ONMARKUPDATE',

	ONADDMARK: 'ONADDMARK',

	ONMARKRANGESHOWORHIDE: 'ONMARKRANGESHOWORHIDE',

	TIPSTEXTSHOW: 'TIPSTEXTSHOW',

	TIPSTEXTHIDE: 'TIPSTEXTHIDE',

	MYSPICCLICK: 'MYSPICCLICK',

	SLGEVENTNOTICE: 'SLGEVENTNOTICE',

	CLICKMOVE: 'CLICKMOVE',

	OPENSTATLAYER: 'OPENSTATLAYER',

	ADDMARKHIDEORSHOW: 'ADDMARKHIDEORSHOW',

	FILLNODEISSHOW: 'FILLNODEISSHOW',
};
